# Generated by Django 2.2.7 on 2019-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20191122_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5, verbose_name='Has your trip exceeded your expectations'),
        ),
    ]
