# Generated by Django 2.2.7 on 2019-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20191124_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='What was the most memorable moment with us?'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Where can we improve?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5, verbose_name='Has your trip exceeded your expectations?'),
        ),
    ]
