# Generated by Django 2.2.7 on 2019-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20191124_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_1',
            field=models.CharField(blank=True, choices=[('Check-in', 'Check-in'), ('Waiter', 'Waiter')], max_length=50, verbose_name='test'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_2',
            field=models.CharField(blank=True, choices=[('Cleanness', 'Cleanness'), ('Bed', 'Bed'), ('Bathroom', 'Bathroom')], max_length=50, verbose_name='test'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_3',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50, verbose_name='test'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_4',
            field=models.CharField(blank=True, choices=[('Kindness', 'Kindness'), ('Knowledge', 'Knowledge'), ('Vehichle', 'Vehichle')], max_length=50, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Has your trip exceeded your expectations?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_2',
            field=models.TextField(blank=True, max_length=200, verbose_name='What was the most memorable moment with us?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3',
            field=models.CharField(blank=True, choices=[('Welcome', 'Welcome'), ('Room', 'Room'), ('Food', 'Food'), ('Guiding', 'Guiding')], max_length=20, verbose_name='Where can we improve?'),
        ),
    ]
