# Generated by Django 2.2.7 on 2020-01-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20191124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_1',
            field=models.CharField(choices=[(None, ''), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=5, verbose_name='Has your trip exceeded your expectations?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3',
            field=models.CharField(choices=[('Welcome', 'Welcome'), ('Room', 'Room'), ('Food', 'Food'), ('Guiding', 'Guiding')], default='', max_length=20, verbose_name='Where can we improve?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_1',
            field=models.CharField(choices=[('Check-in', 'Check-in'), ('Waiter', 'Waiter')], default='', max_length=50, verbose_name='Welcome improvements'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_2',
            field=models.CharField(blank=True, choices=[('Cleanness', 'Cleanness'), ('Bed', 'Bed'), ('Bathroom', 'Bathroom')], max_length=50, verbose_name='Room improvements'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_3',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50, verbose_name='Food improvements'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_4',
            field=models.CharField(blank=True, choices=[('Kindness', 'Kindness'), ('Knowledge', 'Knowledge'), ('Vehichle', 'Vehichle')], max_length=50, verbose_name='Guiding improvements'),
        ),
    ]
