# Generated by Django 2.2.7 on 2020-01-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20200106_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3',
            field=models.CharField(blank=True, choices=[('Welcome', 'Welcome'), ('Room', 'Room'), ('Food', 'Food'), ('Guiding', 'Guiding')], default='', max_length=20, verbose_name='Where can we improve?'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='question_3_subquestion_1',
            field=models.CharField(blank=True, choices=[('Check-in', 'Check-in'), ('Waiter', 'Waiter')], default='', max_length=50, verbose_name='Welcome improvements'),
        ),
    ]
